In [48]:
from bs4 import BeautifulSoup
import requests

In [49]:
url = 'https://www.fortuneindia.com/fortune-500/company-listing/?year=2022&per_page=500&page=1&sort=current-rank&type=asec'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [50]:
print(soup)

<!DOCTYPE html>
<html lang="en">
<head>
<title>Fortune India: Business News, Strategy, Finance and Corporate Insight</title>
<meta content="Fortune India 500 Ranking | Fortune India" name="title"/>
<meta content="Fortune India 500 is the definitive ranking of India's 500 largest corporations | Fortune India" itemprop="description" name="description"/>
<meta content="https://fea.assettype.com/abp/assets/500-bbd82aacac.jpg" name="image"/>
<meta content="Fortune India 500 Ranking | Fortune India" property="og:title"/>
<meta content="Fortune India 500 is the definitive ranking of India's 500 largest corporations | Fortune India" property="og:description"/>
<meta content="https://fea.assettype.com/abp/assets/500-bbd82aacac.jpg" property="og:image"/>
<meta content="Fortune India 500 Ranking | Fortune India" name="twitter:title"/>
<meta content="Fortune India 500 is the definitive ranking of India's 500 largest corporations | Fortune India" name="twitter:description"/>
<meta content="https://fea.assettype.com/abp/assets/500-bbd82aacac.jpg" name="twitter:image"/>
<title>Fortune India 500 Ranking | Fortune India</title>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"/>
<meta charset="utf-8"/>
<link href="/manifest.json" rel="manifest"/>
<link href="https://www.fortuneindia.com/fortune-500" rel="canonical"/>
<!-- Favicon icon starts -->
<link href="https://fea.assettype.com/abp/assets/favicons/apple-icon-57x57-d132f1c328.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="https://fea.assettype.com/abp/assets/favicons/apple-icon-60x60-9bfa66773e.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="https://fea.assettype.com/abp/assets/favicons/apple-icon-72x72-9c75cae987.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="https://fea.assettype.com/abp/assets/favicons/apple-icon-76x76-15f014ee3e.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://fea.assettype.com/abp/assets/favicons/apple-icon-114x114-e312f524d0.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="https://fea.assettype.com/abp/assets/favicons/apple-icon-120x120-163decd241.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://fea.assettype.com/abp/assets/favicons/apple-icon-144x144-d115a2d89c.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="https://fea.assettype.com/abp/assets/favicons/apple-icon-152x152-084a96997f.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://fea.assettype.com/abp/assets/favicons/apple-icon-180x180-460106316a.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://fea.assettype.com/abp/assets/favicons/android-icon-192x192-f98f331cd2.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="https://fea.assettype.com/abp/assets/favicons/favicon-32x32-b20f1e0ebb.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://fea.assettype.com/abp/assets/favicons/favicon-96x96-6434980bfe.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="https://fea.assettype.com/abp/assets/favicons/favicon-16x16-4cc07303f8.png" rel="icon" sizes="16x16" type="image/png"/>
<!-- Favicon icon Ends -->
<link href="https://fea.assettype.com/abp/assets/application-4c04fbd20d.css" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,500,600,700,700i,900|Open+Sans:400,600,700,800" rel="stylesheet"/>
<script src="https://www.gstatic.com/charts/loader.js" type="text/javascript"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet"/>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<!-- Google Tag Manager -->
<script>
          (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-KDCKX8M');
      </script>
<!-- End Google Tag Manager -->
<script>
      var googletag = googletag || {};
      googletag.cmd = googletag.cmd || [];

      googletag.cmd.push(function () {

        var mapping1 = googletag.sizeMapping().
            addSize([1, 1 ], [[320, 50], [320,100], [300,250]]). // Mobile
            addSize([810, 200 ], []).
            addSize([600, 500 ], []).
            build();

        var mapping2 = googletag.sizeMapping().
            addSize([1, 1 ], [300, 250]). // Mobile
            addSize([810, 200 ], []).
            addSize([600, 500 ], []).
            build();

        var mapping3 = googletag.sizeMapping().
            addSize([1, 1 ], [1, 1]). // Mobile
            addSize([780, 200 ], []).
            build();

        var mapping4 = googletag.sizeMapping().
            addSize([780, 200 ], [[728, 90], [970,90]]). // Desktop
            addSize([0, 0 ], []).
            build();

        var mapping5 = googletag.sizeMapping().
            addSize([780, 200 ], [[300, 250], [250,250], [336,280]]). // Desktop
            addSize([0, 0 ], []).
            build();

        var mapping6 = googletag.sizeMapping().
            addSize([780, 200 ], [1, 1]). // Desktop
            addSize([0, 0 ], []).
            build();

        var mapping7 = googletag.sizeMapping().
        		addSize([810, 200 ], ['fluid']). // Desktop
        		addSize([0, 0 ], []).
        		build();

        var mapping8 = googletag.sizeMapping().
            addSize([1, 1 ], [300, 100]). // Mobile
            addSize([810, 200 ], []).
            addSize([600, 500 ], []).
            build();

        var mapping9 = googletag.sizeMapping().
                    addSize([780, 200 ], [1140, 200]). // Desktop
                    addSize([0, 0 ], []).
                    build();

        var mapping10 = googletag.sizeMapping().
            addSize([900,90], [970, 250]).
            addSize([0, 0], [320, 100]).
            build();

        var mapping11 = googletag.sizeMapping().
            addSize([900,90], [728, 90]).
            addSize([0, 0], [300, 250]).
            build();

        var mapping12 = googletag.sizeMapping().
            addSize([900,90], [728, 90]).
            addSize([0, 0], [320, 50]).
            build();

        var REFRESH_KEY = 'refresh';
        var REFRESH_VALUE = 'true';

                                          googletag.defineSlot('/1009127,22665122437/FortuneIndia_Top', [728, 90], 'div-gpt-ad-1501150058174-0').defineSizeMapping(mapping4).addService(googletag.pubads()); // Section Header
        googletag.defineSlot('/1009127,22665122437/FortuneIndia_Top', [[300, 100], [320, 50], [300, 250]], 'div-gpt-ad-1501150058174-5').defineSizeMapping(mapping1).addService(googletag.pubads()); // Section Mobile Header
        googletag.defineSlot('/1009127,22665122437/FortuneIndia_Bottom', [[728, 90], [320, 50]], 'div-gpt-ad-1501150058178-9').defineSizeMapping(mapping12).addService(googletag.pubads()) // Section Footer Mobile
        googletag.defineSlot('/1009127,22665122437/FortuneIndia_RHS_1', [300, 250], 'div-gpt-ad-1501150058174-2').defineSizeMapping(mapping5).addService(googletag.pubads()); // Section RHS 1
        googletag.defineSlot('/1009127,22665122437/FortuneIndia_RHS_1', [300, 250], 'div-gpt-ad-1501150058174-6').defineSizeMapping(mapping2).addService(googletag.pubads()); // Section RHS 1 Mobile
        googletag.defineSlot('/1009127,22665122437/FortuneIndia_RHS_2', [300, 250], 'div-gpt-ad-1501150058174-6-3').defineSizeMapping(mapping2).addService(googletag.pubads()); // Section RHS 1 Mobile 2
        googletag.defineSlot('/1009127,22665122437/FortuneIndia_RHS_2', [300, 250], 'div-gpt-ad-1501150058174-3').defineSizeMapping(mapping5).addService(googletag.pubads()); // Section RHS 2
        googletag.defineSlot('/1009127,22665122437/FortuneIndia_RHS_2', [300, 250], 'div-gpt-ad-1501150058174-6-2').defineSizeMapping(mapping2).addService(googletag.pubads()); // Section RHS 2 Mobile
        // googletag.defineOutOfPageSlot('/1088475/FT_Desk_1x1', 'div-gpt-ad-1501150058174-4').defineSizeMapping(mapping6).addService(googletag.pubads()); // Out of page Section Slot
        // googletag.defineOutOfPageSlot('/1088475/FT_Mob_1x1', 'div-gpt-ad-1501150058174-8').defineSizeMapping(mapping3).addService(googletag.pubads()); // Out of page Story Section Mobile
                        googletag.pubads().setTargeting("Homepage", "Section");
        googletag.pubads().enableSingleRequest();
        googletag.pubads().addEventListener('slotRenderEnded', function(event) {
          qtReady.push(function () {
            if (event.slot.getSlotElementId() == "div-gpt-ad-1511508149071-0" && !event.isEmpty) {
              // Hide most read 2nd story so that ad can overlap it.
              $('.mostread__ad').css('bottom', 0);
            }
          });
        });
        googletag.pubads().collapseEmptyDivs();
        googletag.enableServices();
      });
    </script>
<!-- Qlitics Snippet -->
<script>
      window.qlitics = window.qlitics || function () {
        (qlitics.q = qlitics.q || []).push(arguments);
      };
      qlitics('init');
      qlitics('track', 'page-view', {'page-type': 'fortune500'});
    </script>
<script async="" src="/qlitics.js"></script>
<!-- End Qlitics Snippet -->
<!-- google custom search -->
<script>
      (function() {
        var cx = "008330974280404948002:jwejrnee1kl";
        var gcse = document.createElement('script');
        gcse.type = 'text/javascript';
        gcse.async = true;
        gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(gcse, s);
      })();
    </script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-81734507-1"></script>
<script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-81734507-1');
    </script>
<script async="" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4463447431408689"></script>
</head>
<body>
<!-- Google Tag Manager -->
<noscript>
<iframe height="0" src="//www.googletagmanager.com/ns.html?id=GTM-TVDVWK" style="display:none;visibility:hidden" width="0">
</iframe>
</noscript>
<!-- End of Google Tag Manager -->
<script type="text/javascript">var qtReady = qtReady || [];</script>
<div class="body-container">
<!-- /1088475/Ft_Desk_728x90_Header -->
<div class="top-ad-container" id="div-gpt-ad-1501150058174-0">
<script>
            googletag.cmd.push(function() { googletag.display('div-gpt-ad-1501150058174-0'); });
          </script>
</div>
<header>
<div class="header">
<button class="toggle-main-nav" id="toggle-main-nav">
<span></span>
<span></span>
<span></span>
<span></span>
</button>
<div class="site-logo-container">
<a class="site-logo" href="/">FortuneIndia</a>
</div>
<div class="header-search">
<div class="header-search__input-container">
<form action="/search" method="get">
<input class="header-search__input" id="story-search-input" name="q" placeholder="Search.." type="search"/>
</form>
</div>
<button class="header-search__icon" id="toggle-search-bar">
<i class="fa fa-search fa-2x fa-white"></i>
</button>
</div>
</div>
<div class="toolbar js-toolbar-toggle">
<div class="toolbar-inner">
<span class="menu-item header-item quick-links">Quick Links :</span>
<ul class="menu-list">
<li class="menu-item hamburger-item">
<form action="/search" class="search-form" method="GET">
<div class="form-el">
<input class="search-text-input" id="js-hamburger-search-input" name="q" placeholder="Search" type="text"/>
<button class="button-holder">
<i class="fa fa-search"></i>
</button>
</div>
</form>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="/fortune-500?year=2022">Fortune 500 India</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="/40under40">40 Under 40</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="/mpw?year=2023">Most Powerful Women</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="/budget-2023">Budget 2023</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="India's richest">India's Richest</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="/next-500">The Next 500</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="https://fortuneindia.com/b-school/2022" rel="nofollow" target="_blank">Best B-Schools</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="/opinion">Opinion</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="/multimedia">Multimedia</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="/first-edit">First Edit</a>
</li>
<li class="menu-item header-item">
<a class="menu-anchor" href="/events/fortune-indias-the-next-500-event-awards-ceremony-on-july-7-in-new-delhi/113171">Events</a>
</li>
<li class="menu-item hamburger-item">
<div class="menu-anchor section-anchor social-media" title="Social share">
<ul>
<li><a class="social-icon" href="https://twitter.com/FortuneIndia" target="_blank"> <i class="fa fa-twitter bgm"></i></a></li>
<li><a class="social-icon" href="https://www.facebook.com/fortuneind/" target="_blank"> <i class="fa fa-facebook"></i></a></li>
<li><a class="social-icon" href="https://plus.google.com/100287022162827136313" target="_blank"> <i class="fa fa-google-plus"></i></a></li>
<li><a class="social-icon" href="mailto:digital@fortuneindia.com" target="_blank"> <i class="fa fa-envelope"></i></a></li>
<li><a class="social-icon" href="https://www.linkedin.com/company/fortune-india" target="_blank"> <i class="fa fa-linkedin"></i></a></li>
<li><a class="social-icon" href="https://www.instagram.com/fortune.india/" target="_blank"> <i class="fa fa-instagram"></i></a></li>
<li><a class="social-icon" href="https://www.youtube.com/channel/UCKomZAH0tqC25GJqe3Spykw" target="_blank"> <i class="fa fa-youtube-play"></i></a></li>
</ul>
</div>
</li>
</ul>
</div>
</div>
<div class="sidenav" id="sidenav">
<ul class="menu-list">
<li class="menu-item hamburger-item">
<form action="/search" class="search-form" method="GET">
<div class="form-el">
<input class="search-text-input" id="js-hamburger-search-input" name="q" placeholder="Search" type="text"/>
<button class="button-holder">
<i class="fa fa-search"></i>
</button>
</div>
</form>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/fortune-500?year=2022">Fortune 500 India</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/40under40">40 Under 40</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/mpw?year=2023">Most Powerful Women</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/next-500">The Next 500</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/b-school/2022">Best B-Schools</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor section-underline" href="/allrankings">All Rankings</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/events/fortune-indias-the-next-500-event-awards-ceremony-on-july-7-in-new-delhi/113171">Events</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/macro">Macro</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/enterprise">Enterprise</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/technology">Technology</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/reviews">Reviews</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/venture">Venture</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/investing">Investing</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/multimedia">Multimedia</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/fortune-india-exchange">Fortune India Exchange</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/bystander">Bystander</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/opinion">Opinion</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/infographics">Infographics</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/ideas">Ideas</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/long-reads">Long Reads</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/people">People</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="https://www.amazon.in/dp/B0C9YTMDDS" rel="nofollow" target="_blank">Buy on Amazon</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="/polemicist">Polemicist</a>
</li>
<li class="menu-item hamburger-item">
<a class="menu-anchor section-anchor" href="https://shop.yudirect.biz/FortuneIndia/Fortune.php" rel="nofollow" target="_blank">Annual Subscription</a>
</li>
<li class="menu-item hamburger-item">
<div class="menu-anchor section-anchor social-media" title="Social share">
<ul>
<li><a class="social-icon" href="https://twitter.com/FortuneIndia" target="_blank"> <i class="fa fa-twitter bgm"></i></a></li>
<li><a class="social-icon" href="https://www.facebook.com/fortuneind/" target="_blank"> <i class="fa fa-facebook"></i></a></li>
<li><a class="social-icon" href="https://plus.google.com/100287022162827136313" target="_blank"> <i class="fa fa-google-plus"></i></a></li>
<li><a class="social-icon" href="mailto:digital@fortuneindia.com" target="_blank"> <i class="fa fa-envelope"></i></a></li>
<li><a class="social-icon" href="https://www.linkedin.com/company/fortune-india" target="_blank"> <i class="fa fa-linkedin"></i></a></li>
<li><a class="social-icon" href="https://www.instagram.com/fortune.india/" target="_blank"> <i class="fa fa-instagram"></i></a></li>
<li><a class="social-icon" href="https://www.youtube.com/channel/UCKomZAH0tqC25GJqe3Spykw" target="_blank"> <i class="fa fa-youtube-play"></i></a></li>
</ul>
</div>
</li>
</ul>
</div>
</header>
<main class="layout-content">
<div id="container">
<!-- /1088475/Ft_Mob_320x50_Header -->
<div class="ad-mob-container" id="div-gpt-ad-1501150058174-5">
<script>
			googletag.cmd.push(function() { googletag.display('div-gpt-ad-1501150058174-5'); });
		</script>
</div>
<div class="landing-page">
<div class="container">
<div class="lead-section">
<h1 class="headline table-main-headline">Fortune India 500: <span class="year">2022</span></h1>
</div>
<div class="f-500-listing-container" style="width: 100%">
<div class="top-container">
<form action="javascript:searchBox()" class="search-box" id="search_filter_box" method="GET" onreset="javascript:resetSearchBox()">
<input class="search-text-input" id="filter" name="search" placeholder="Search Company" type="text" value=""/>
<button class="clear-text" type="reset">×</button>
<button class="button-submit" type="submit">
            Search
          </button>
</form>
<div class="years-select">

In [51]:
world_titles = soup.find_all('span')

In [52]:
world_titles

[<span></span>,
 <span></span>,
 <span></span>,
 <span></span>,
 <span class="menu-item header-item quick-links">Quick Links :</span>,
 <span class="year">2022</span>,
 <span class="year-select selected" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2022;">2022</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2021;">2021</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2020;">2020</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2019;">2019</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2018;">2018</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2017;">2017</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2016;">2016</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2015;">2015</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2014;">2014</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2013;">2013</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2012;">2012</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2011;">2011</span>,
 <span class="year-select" onclick="javascript:location.href = '/' + 'fortune-500/company-listing/?year='+ 2010;">2010</span>,
 <span>2022</span>,
 <span>2021</span>,
 <span>Change</span>,
 <span>Company</span>,
 <span>Ownership</span>,
 <span>Industry</span>,
 <span>Rs cr</span>,
 <span>YoY change %</span>,
 <span>Rs cr</span>,
 <span>YoY change %</span>,
 <span>Rs cr</span>,
 <span>Rank</span>,
 <span>YoY change %</span>,
 <span>% of total income</span>,
 <span>Rs cr</span>,
 <span>% of Ebitda</span>,
 <span>Rs cr</span>,
 <span>Rs cr</span>,
 <span>(x)</span>,
 <span>Rs cr</span>,
 <span>Rank</span>,
 <span>YoY change %</span>,
 <span>Rs cr</span>,
 <span>Rank</span>,
 <span>(%)</span>,
 <span>(%)</span>,
 <span>(in nos)</span>,
 <span>Rank</span>,
 <span>RS Crore</span>,
 <span>(%)</span>,
 <span>page</span>,
 <span>of 1</span>,
 <span class="head">FOOTNOTES:</span>,
 <span class="ad-header">Advertisement</span>,
 <span class="ad-header">Advertisement</span>]

In [58]:
world_table_titles = [title.text.strip() for title in world_titles]



# Define a list of valid titles
valid_titles = ["2022", "2021", "Change", "Company", "Ownership", "Industry", "Rs cr", "YoY change %",
                "Rs cr", "YoY change %", "Rs cr", "Rank", "YoY change %", "% of total income", "Rs cr",
                "% of Ebitda", "Rs cr", "Rs cr", "(x)", "Rs cr", "Rank", "YoY change %", "Rs cr", "Rank",
                "(%)", "(%)", "(in nos)", "Rank", "RS Crore", "(%)"]

# Filter out unwanted titles
filtered_titles = [title for title in world_table_titles if title in valid_titles]


filtered_titles_without_first_three = filtered_titles[3:]

print(filtered_titles_without_first_three)

['2022', '2021', 'Change', 'Company', 'Ownership', 'Industry', 'Rs cr', 'YoY change %', 'Rs cr', 'YoY change %', 'Rs cr', 'Rank', 'YoY change %', '% of total income', 'Rs cr', '% of Ebitda', 'Rs cr', 'Rs cr', '(x)', 'Rs cr', 'Rank', 'YoY change %', 'Rs cr', 'Rank', '(%)', '(%)', '(in nos)', 'Rank', 'RS Crore', '(%)']

In [59]:
import pandas as pd

df = pd.DataFrame(columns = filtered_titles_without_first_three)

df

Empty DataFrame
Columns: [2022, 2021, Change, Company, Ownership, Industry, Rs cr, YoY change %, Rs cr, YoY change %, Rs cr, Rank, YoY change %, % of total income, Rs cr, % of Ebitda, Rs cr, Rs cr, (x), Rs cr, Rank, YoY change %, Rs cr, Rank, (%), (%), (in nos), Rank, RS Crore, (%)]
Index: []

[0 rows x 30 columns]

In [60]:
column_data = soup.find_all('tr', attrs={'class':'mpw-tr company-details-row'})

In [61]:
column_data

[<tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">1</td>
 <td class="f-500-row-td align-center">1</td>
 <td class="f-500-row-td align-center">0</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/reliance-industries?year=2022" title="Reliance Industries">
                           Reliance Industries

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       Mukesh Ambani
                                           </td>
 <td class="f-500-row-td industry" width="50%">Oil &amp; Gas</td>
 <td class="f-500-row-td align-right">739518</td>
 <td class="f-500-row-td align-right">43.81</td>
 <td class="f-500-row-td align-right">699962</td>
 <td class="f-500-row-td align-right">49.91</td>
 <td class="f-500-row-td align-right">60705</td>
 <td class="f-500-row-td align-center">1</td>
 <td class="f-500-row-td align-right">23.56</td>
 <td class="f-500-row-td align-right">8.21</td>
 <td class="f-500-row-td align-right">14584</td>
 <td class="f-500-row-td align-right">13.21</td>
 <td class="f-500-row-td align-right">36178</td>
 <td class="f-500-row-td align-right">319158</td>
 <td class="f-500-row-td align-right">0.41</td>
 <td class="f-500-row-td align-right">1222627</td>
 <td class="f-500-row-td align-center">8.00</td>
 <td class="f-500-row-td align-right">11.54</td>
 <td class="f-500-row-td align-right">779485</td>
 <td class="f-500-row-td align-center">1.00</td>
 <td class="f-500-row-td align-right">9.17</td>
 <td class="f-500-row-td align-right">9.36</td>
 <td class="f-500-row-td align-right">342982</td>
 <td class="f-500-row-td align-center">2</td>
 <td class="f-500-row-td align-right">1681013</td>
 <td class="f-500-row-td align-right">0.78</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">2</td>
 <td class="f-500-row-td align-center">NAP</td>
 <td class="f-500-row-td align-center">NEW</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/lic?year=2022" title="LIC">
                           LIC

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       GoI
                                           </td>
 <td class="f-500-row-td industry" width="50%">Financial Services</td>
 <td class="f-500-row-td align-right">724744</td>
 <td class="f-500-row-td align-right">2.99</td>
 <td class="f-500-row-td align-right">723606</td>
 <td class="f-500-row-td align-right">4.73</td>
 <td class="f-500-row-td align-right">4125</td>
 <td class="f-500-row-td align-center">57</td>
 <td class="f-500-row-td align-right">38.69</td>
 <td class="f-500-row-td align-right">0.57</td>
 <td class="f-500-row-td align-right">0</td>
 <td class="f-500-row-td align-right">NAP</td>
 <td class="f-500-row-td align-right">44724</td>
 <td class="f-500-row-td align-right">0</td>
 <td class="f-500-row-td align-right">0.00</td>
 <td class="f-500-row-td align-right">4182536</td>
 <td class="f-500-row-td align-center">2.00</td>
 <td class="f-500-row-td align-right">11.64</td>
 <td class="f-500-row-td align-right">11336</td>
 <td class="f-500-row-td align-center">130.00</td>
 <td class="f-500-row-td align-right">45.28</td>
 <td class="f-500-row-td align-right">0.31</td>
 <td class="f-500-row-td align-right">NAVL</td>
 <td class="f-500-row-td align-center">NAP</td>
 <td class="f-500-row-td align-right">433115</td>
 <td class="f-500-row-td align-right">-30.85</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">3</td>
 <td class="f-500-row-td align-center">3</td>
 <td class="f-500-row-td align-center">0</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/indian-oil-corporation?year=2022" title="Indian Oil Corporation">
                           Indian Oil Corporation

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       GoI
                                           </td>
 <td class="f-500-row-td industry" width="50%">Oil &amp; Gas</td>
 <td class="f-500-row-td align-right">607365</td>
 <td class="f-500-row-td align-right">62.04</td>
 <td class="f-500-row-td align-right">589336</td>
 <td class="f-500-row-td align-right">61.93</td>
 <td class="f-500-row-td align-right">25102</td>
 <td class="f-500-row-td align-center">8</td>
 <td class="f-500-row-td align-right">16.01</td>
 <td class="f-500-row-td align-right">4.13</td>
 <td class="f-500-row-td align-right">4301</td>
 <td class="f-500-row-td align-right">9.23</td>
 <td class="f-500-row-td align-right">1820</td>
 <td class="f-500-row-td align-right">132020</td>
 <td class="f-500-row-td align-right">0.99</td>
 <td class="f-500-row-td align-right">272852</td>
 <td class="f-500-row-td align-center">27.00</td>
 <td class="f-500-row-td align-right">16.36</td>
 <td class="f-500-row-td align-right">133535</td>
 <td class="f-500-row-td align-center">8.00</td>
 <td class="f-500-row-td align-right">20.97</td>
 <td class="f-500-row-td align-right">15.29</td>
 <td class="f-500-row-td align-right">31254</td>
 <td class="f-500-row-td align-center">26</td>
 <td class="f-500-row-td align-right">108577</td>
 <td class="f-500-row-td align-right">-13.70</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">4</td>
 <td class="f-500-row-td align-center">4</td>
 <td class="f-500-row-td align-center">0</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/ongc?year=2022" title="ONGC">
                           ONGC

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       GoI
                                           </td>
 <td class="f-500-row-td industry" width="50%">Oil &amp; gas</td>
 <td class="f-500-row-td align-right">502474</td>
 <td class="f-500-row-td align-right">54.51</td>
 <td class="f-500-row-td align-right">491270</td>
 <td class="f-500-row-td align-right">61.66</td>
 <td class="f-500-row-td align-right">45522</td>
 <td class="f-500-row-td align-center">2</td>
 <td class="f-500-row-td align-right">179.20</td>
 <td class="f-500-row-td align-right">9.06</td>
 <td class="f-500-row-td align-right">5696</td>
 <td class="f-500-row-td align-right">7.32</td>
 <td class="f-500-row-td align-right">6841</td>
 <td class="f-500-row-td align-right">121986</td>
 <td class="f-500-row-td align-right">0.47</td>
 <td class="f-500-row-td align-right">444489</td>
 <td class="f-500-row-td align-center">17.00</td>
 <td class="f-500-row-td align-right">6.09</td>
 <td class="f-500-row-td align-right">259503</td>
 <td class="f-500-row-td align-center">3.00</td>
 <td class="f-500-row-td align-right">20.52</td>
 <td class="f-500-row-td align-right">14.62</td>
 <td class="f-500-row-td align-right">27165</td>
 <td class="f-500-row-td align-center">36</td>
 <td class="f-500-row-td align-right">188068</td>
 <td class="f-500-row-td align-right">-6.05</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">5</td>
 <td class="f-500-row-td align-center">2</td>
 <td class="f-500-row-td align-center">-3</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/state-bank-of-india?year=2022" title="State Bank of India">
                           State Bank of India

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       GoI
                                           </td>
 <td class="f-500-row-td industry" width="50%">Banking</td>
 <td class="f-500-row-td align-right">406973</td>
 <td class="f-500-row-td align-right">5.61</td>
 <td class="f-500-row-td align-right">289973</td>
 <td class="f-500-row-td align-right">4.26</td>
 <td class="f-500-row-td align-right">35374</td>
 <td class="f-500-row-td align-center">6</td>
 <td class="f-500-row-td align-right">57.88</td>
 <td class="f-500-row-td align-right">8.69</td>
 <td class="f-500-row-td align-right">156194</td>
 <td class="f-500-row-td align-right">NAP</td>
 <td class="f-500-row-td align-right">398905</td>
 <td class="f-500-row-td align-right">4536571</td>
 <td class="f-500-row-td align-right">0.00</td>
 <td class="f-500-row-td align-right">5371426</td>
 <td class="f-500-row-td align-center">1.00</td>
 <td class="f-500-row-td align-right">10.64</td>
 <td class="f-500-row-td align-right">282210</td>
 <td class="f-500-row-td align-center">2.00</td>
 <td class="f-500-row-td align-right">13.61</td>
 <td class="f-500-row-td align-right">0.69</td>
 <td class="f-500-row-td align-right">245652</td>
 <td class="f-500-row-td align-center">6</td>
 <td class="f-500-row-td align-right">447533</td>
 <td class="f-500-row-td align-right">13.04</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">6</td>
 <td class="f-500-row-td align-center">6</td>
 <td class="f-500-row-td align-center">0</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/bharat-petroleum-corporation?year=2022" title="Bharat Petroleum Corporation">
                           Bharat Petroleum Corporation

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       GoI
                                           </td>
 <td class="f-500-row-td industry" width="50%">Oil &amp; Gas</td>
 <td class="f-500-row-td align-right">355772</td>
 <td class="f-500-row-td align-right">47.36</td>
 <td class="f-500-row-td align-right">346791</td>
 <td class="f-500-row-td align-right">50.67</td>
 <td class="f-500-row-td align-right">11682</td>
 <td class="f-500-row-td align-center">26</td>
 <td class="f-500-row-td align-right">-27.74</td>
 <td class="f-500-row-td align-right">3.28</td>
 <td class="f-500-row-td align-right">2606</td>
 <td class="f-500-row-td align-right">13.62</td>
 <td class="f-500-row-td align-right">2237</td>
 <td class="f-500-row-td align-right">64534</td>
 <td class="f-500-row-td align-right">1.24</td>
 <td class="f-500-row-td align-right">118219</td>
 <td class="f-500-row-td align-center">55.00</td>
 <td class="f-500-row-td align-right">7.94</td>
 <td class="f-500-row-td align-right">51906</td>
 <td class="f-500-row-td align-center">33.00</td>
 <td class="f-500-row-td align-right">22.15</td>
 <td class="f-500-row-td align-right">16.37</td>
 <td class="f-500-row-td align-right">8594</td>
 <td class="f-500-row-td align-center">118</td>
 <td class="f-500-row-td align-right">76165</td>
 <td class="f-500-row-td align-right">-24.86</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">7</td>
 <td class="f-500-row-td align-center">5</td>
 <td class="f-500-row-td align-center">-2</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/tata-motors?year=2022" title="Tata Motors">
                           Tata Motors

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       Tata Group
                                           </td>
 <td class="f-500-row-td industry" width="50%">Auto</td>
 <td class="f-500-row-td align-right">280027</td>
 <td class="f-500-row-td align-right">12.70</td>
 <td class="f-500-row-td align-right">278454</td>
 <td class="f-500-row-td align-right">11.47</td>
 <td class="f-500-row-td align-right">-11441</td>
 <td class="f-500-row-td align-center">499</td>
 <td class="f-500-row-td align-right">0.00</td>
 <td class="f-500-row-td align-right">NAP</td>
 <td class="f-500-row-td align-right">9312</td>
 <td class="f-500-row-td align-right">38.83</td>
 <td class="f-500-row-td align-right">40669</td>
 <td class="f-500-row-td align-right">146449</td>
 <td class="f-500-row-td align-right">3.29</td>
 <td class="f-500-row-td align-right">221106</td>
 <td class="f-500-row-td align-center">38.00</td>
 <td class="f-500-row-td align-right">-2.78</td>
 <td class="f-500-row-td align-right">44561</td>
 <td class="f-500-row-td align-center">41.00</td>
 <td class="f-500-row-td align-right">NAP</td>
 <td class="f-500-row-td align-right">1.04</td>
 <td class="f-500-row-td align-right">25588</td>
 <td class="f-500-row-td align-center">43</td>
 <td class="f-500-row-td align-right">160911</td>
 <td class="f-500-row-td align-right">-15.05</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">8</td>
 <td class="f-500-row-td align-center">9</td>
 <td class="f-500-row-td align-center">1</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/tata-steel?year=2022" title="Tata Steel">
                           Tata Steel

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       Tata Group
                                           </td>
 <td class="f-500-row-td industry" width="50%">Iron &amp; Steel</td>
 <td class="f-500-row-td align-right">253797</td>
 <td class="f-500-row-td align-right">62.32</td>
 <td class="f-500-row-td align-right">243959</td>
 <td class="f-500-row-td align-right">55.91</td>
 <td class="f-500-row-td align-right">40154</td>
 <td class="f-500-row-td align-center">3</td>
 <td class="f-500-row-td align-right">436.08</td>
 <td class="f-500-row-td align-right">15.82</td>
 <td class="f-500-row-td align-right">5462</td>
 <td class="f-500-row-td align-right">8.73</td>
 <td class="f-500-row-td align-right">15899</td>
 <td class="f-500-row-td align-right">75561</td>
 <td class="f-500-row-td align-right">0.66</td>
 <td class="f-500-row-td align-right">207633</td>
 <td class="f-500-row-td align-center">40.00</td>
 <td class="f-500-row-td align-right">14.42</td>
 <td class="f-500-row-td align-right">113546</td>
 <td class="f-500-row-td align-center">10.00</td>
 <td class="f-500-row-td align-right">44.54</td>
 <td class="f-500-row-td align-right">29.16</td>
 <td class="f-500-row-td align-right">35927</td>
 <td class="f-500-row-td align-center">24</td>
 <td class="f-500-row-td align-right">136734</td>
 <td class="f-500-row-td align-right">-21.69</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">9</td>
 <td class="f-500-row-td align-center">13</td>
 <td class="f-500-row-td align-center">4</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/hindalco-industries?year=2022" title="Hindalco Industries">
                           Hindalco Industries

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       Aditya Birla Group
                                           </td>
 <td class="f-500-row-td industry" width="50%">Metals &amp; Mining</td>
 <td class="f-500-row-td align-right">206795</td>
 <td class="f-500-row-td align-right">52.63</td>
 <td class="f-500-row-td align-right">195059</td>
 <td class="f-500-row-td align-right">47.76</td>
 <td class="f-500-row-td align-right">13730</td>
 <td class="f-500-row-td align-center">19</td>
 <td class="f-500-row-td align-right">294.20</td>
 <td class="f-500-row-td align-right">6.64</td>
 <td class="f-500-row-td align-right">3768</td>
 <td class="f-500-row-td align-right">13.64</td>
 <td class="f-500-row-td align-right">17392</td>
 <td class="f-500-row-td align-right">64486</td>
 <td class="f-500-row-td align-right">0.82</td>
 <td class="f-500-row-td align-right">152037</td>
 <td class="f-500-row-td align-center">44.00</td>
 <td class="f-500-row-td align-right">5.58</td>
 <td class="f-500-row-td align-right">78191</td>
 <td class="f-500-row-td align-center">17.00</td>
 <td class="f-500-row-td align-right">18.97</td>
 <td class="f-500-row-td align-right">15.45</td>
 <td class="f-500-row-td align-right">21151</td>
 <td class="f-500-row-td align-center">58</td>
 <td class="f-500-row-td align-right">101778</td>
 <td class="f-500-row-td align-right">-14.30</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">10</td>
 <td class="f-500-row-td align-center">7</td>
 <td class="f-500-row-td align-center">-3</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/tata-consultancy-services?year=2022" title="Tata Consultancy Services">
                           Tata Consultancy Services

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       Tata Group
                                           </td>
 <td class="f-500-row-td industry" width="50%">Infotech</td>
 <td class="f-500-row-td align-right">195772</td>
 <td class="f-500-row-td align-right">17.01</td>
 <td class="f-500-row-td align-right">191754</td>
 <td class="f-500-row-td align-right">16.80</td>
 <td class="f-500-row-td align-right">38327</td>
 <td class="f-500-row-td align-center">4</td>
 <td class="f-500-row-td align-right">18.18</td>
 <td class="f-500-row-td align-right">19.58</td>
 <td class="f-500-row-td align-right">784</td>
 <td class="f-500-row-td align-right">1.48</td>
 <td class="f-500-row-td align-right">18221</td>
 <td class="f-500-row-td align-right">7818</td>
 <td class="f-500-row-td align-right">0.09</td>
 <td class="f-500-row-td align-right">100023</td>
 <td class="f-500-row-td align-center">58.00</td>
 <td class="f-500-row-td align-right">2.98</td>
 <td class="f-500-row-td align-right">88651</td>
 <td class="f-500-row-td align-center">15.00</td>
 <td class="f-500-row-td align-right">44.13</td>
 <td class="f-500-row-td align-right">53.97</td>
 <td class="f-500-row-td align-right">592195</td>
 <td class="f-500-row-td align-center">1</td>
 <td class="f-500-row-td align-right">1265497</td>
 <td class="f-500-row-td align-right">-6.89</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">11</td>
 <td class="f-500-row-td align-center">10</td>
 <td class="f-500-row-td align-center">-1</td>
 <td class="company-name-container f-500-row-td" width="50%">
 <a class="company-name" href="/fortune-500/company-list/hdfc-bank?year=2022" title="HDFC Bank">
                           HDFC Bank

                     </a>
 </td>
 <td class="f-500-row-td" width="50%">
                       Diversified
                                               *
                                           </td>
 <td class="f-500-row-td industry" width="50%">Banking</td>
 <td class="f-500-row-td align-right">167695</td>
 <td class="f-500-row-td align-right">7.58</td>
 <td class="f-500-row-td align-right">135936</td>
 <td class="f-500-row-td align-right">5.74</td>
 <td class="f-500-row-td align-right">38053</td>
 <td class="f-500-row-td align-center">5</td>
 <td class="f-500-row-td align-right">19.54</td>
 <td class="f-500-row-td align-right">22.69</td>
 <td class="f-500-row-td align-right">58584</td>
 <td class="f-500-row-td align-right">NAP</td>
 <td class="f-500-row-td align-right">155386</td>
 <td class="f-500-row-td align-right">1784970</td>
 <td class="f-500-row-td align-right">0.00</td>
 <td class="f-500-row-td align-right">2122934</td>
 <td class="f-500-row-td align-center">3.00</td>
 <td class="f-500-row-td align-right">17.97</td>
 <td class="f-500-row-td align-right">247326</td>
 <td class="f-500-row-td align-center">4.00</td>
 <td class="f-500-row-td align-right">16.69</td>
 <td class="f-500-row-td align-right">1.94</td>
 <td class="f-500-row-td align-right">141579</td>
 <td class="f-500-row-td align-center">8</td>
 <td class="f-500-row-td align-right">802745</td>
 <td class="f-500-row-td align-right">-5.72</td>
 </tr>,
 <tr class="mpw-tr company-details-row">
 <td class="f-500-row-td serial-num">12</td>
 <td class="f-500-row-td align-center">11</td>
 <td class="f-500-row-td align-center">-1</td>

In [62]:
# Initialize an empty list to store rows of data
data_rows = []

# Iterate through the rows of data
for row in column_data:
    # Find all the <td> elements within the current row
    td_elements = row.find_all('td')
    
    # Extract and store the text content of each <td> element with specific class names
    row_data = [td.text.strip() for td in td_elements if td.has_attr('class') ]
    
    # Append the row_data list to the data_rows list
    data_rows.append(row_data)

# Display the resulting list of data rows
for row in data_rows:
    print(row)

['1', '1', '0', 'Reliance Industries', 'Mukesh Ambani', 'Oil & Gas', '739518', '43.81', '699962', '49.91', '60705', '1', '23.56', '8.21', '14584', '13.21', '36178', '319158', '0.41', '1222627', '8.00', '11.54', '779485', '1.00', '9.17', '9.36', '342982', '2', '1681013', '0.78']
['2', 'NAP', 'NEW', 'LIC', 'GoI', 'Financial Services', '724744', '2.99', '723606', '4.73', '4125', '57', '38.69', '0.57', '0', 'NAP', '44724', '0', '0.00', '4182536', '2.00', '11.64', '11336', '130.00', '45.28', '0.31', 'NAVL', 'NAP', '433115', '-30.85']
['3', '3', '0', 'Indian Oil Corporation', 'GoI', 'Oil & Gas', '607365', '62.04', '589336', '61.93', '25102', '8', '16.01', '4.13', '4301', '9.23', '1820', '132020', '0.99', '272852', '27.00', '16.36', '133535', '8.00', '20.97', '15.29', '31254', '26', '108577', '-13.70']
['4', '4', '0', 'ONGC', 'GoI', 'Oil & gas', '502474', '54.51', '491270', '61.66', '45522', '2', '179.20', '9.06', '5696', '7.32', '6841', '121986', '0.47', '444489', '17.00', '6.09', '259503', '3.00', '20.52', '14.62', '27165', '36', '188068', '-6.05']
['5', '2', '-3', 'State Bank of India', 'GoI', 'Banking', '406973', '5.61', '289973', '4.26', '35374', '6', '57.88', '8.69', '156194', 'NAP', '398905', '4536571', '0.00', '5371426', '1.00', '10.64', '282210', '2.00', '13.61', '0.69', '245652', '6', '447533', '13.04']
['6', '6', '0', 'Bharat Petroleum Corporation', 'GoI', 'Oil & Gas', '355772', '47.36', '346791', '50.67', '11682', '26', '-27.74', '3.28', '2606', '13.62', '2237', '64534', '1.24', '118219', '55.00', '7.94', '51906', '33.00', '22.15', '16.37', '8594', '118', '76165', '-24.86']
['7', '5', '-2', 'Tata Motors', 'Tata Group', 'Auto', '280027', '12.70', '278454', '11.47', '-11441', '499', '0.00', 'NAP', '9312', '38.83', '40669', '146449', '3.29', '221106', '38.00', '-2.78', '44561', '41.00', 'NAP', '1.04', '25588', '43', '160911', '-15.05']
['8', '9', '1', 'Tata Steel', 'Tata Group', 'Iron & Steel', '253797', '62.32', '243959', '55.91', '40154', '3', '436.08', '15.82', '5462', '8.73', '15899', '75561', '0.66', '207633', '40.00', '14.42', '113546', '10.00', '44.54', '29.16', '35927', '24', '136734', '-21.69']
['9', '13', '4', 'Hindalco Industries', 'Aditya Birla Group', 'Metals & Mining', '206795', '52.63', '195059', '47.76', '13730', '19', '294.20', '6.64', '3768', '13.64', '17392', '64486', '0.82', '152037', '44.00', '5.58', '78191', '17.00', '18.97', '15.45', '21151', '58', '101778', '-14.30']
['10', '7', '-3', 'Tata Consultancy Services', 'Tata Group', 'Infotech', '195772', '17.01', '191754', '16.80', '38327', '4', '18.18', '19.58', '784', '1.48', '18221', '7818', '0.09', '100023', '58.00', '2.98', '88651', '15.00', '44.13', '53.97', '592195', '1', '1265497', '-6.89']
['11', '10', '-1', 'HDFC Bank', 'Diversified\n                                              *', 'Banking', '167695', '7.58', '135936', '5.74', '38053', '5', '19.54', '22.69', '58584', 'NAP', '155386', '1784970', '0.00', '2122934', '3.00', '17.97', '247326', '4.00', '16.69', '1.94', '141579', '8', '802745', '-5.72']
['12', '11', '-1', 'Larsen & Toubro', 'Diversified', 'Capital Goods', '160962', '9.27', '156521', '15.11', '8669', '30', '-25.15', '5.39', '9235', '37.96', '18953', '125292', '1.52', '221833', '37.00', '-0.78', '82408', '16.00', '13.00', '11.30', '50267', '22', '252441', '14.15']
['13', '8', '-5', 'ICICI Bank', 'Diversified', 'Banking', '157536', '-2.27', '95407', '7.00', '25110', '7', '36.58', '15.94', '41167', 'NAP', '183126', '1252969', '0.00', '1756355', '4.00', '11.37', '178824', '6.00', '15.47', '1.51', '105844', '10', '541104', '13.62']
['14', '24', '10', 'JSW Steel', 'Savitri Devi Jindal', 'Iron & Steel', '152420', '88.69', '146371', '83.33', '20665', '11', '161.22', '13.56', '4968', '12.98', '17383', '72208', '1.07', '144039', '47.00', '24.80', '67297', '21.00', '37.09', '26.82', '12398', '96', '156564', '0.95']
['15', '12', '-3', 'HDFC', 'Diversified\n                                              *', 'NBFC', '144938', '-0.72', '135926', '-2.24', '22595', '9', '20.57', '15.59', '27230', 'NAP', '2629', '507460', '2.82', '700090', '14.00', '14.28', '179853', '5.00', '14.29', '8.59', '6214', '148', '439224', '-13.39']
['16', '14', '-2', 'NTPC', 'GoI', 'Power', '137580', '16.38', '132669', '18.95', '16676', '15', '13.95', '12.12', '9376', '23.29', '4458', '210707', '1.56', '356845', '22.00', '2.75', '135374', '7.00', '12.99', '9.01', 'NAVL', 'NAP', '141394', '35.22']
['17', '20', '3', 'Vedanta', 'Anil Agarwal', 'Metals & Mining', '137381', '51.55', '132732', '50.80', '18802', '12', '62.06', '13.69', '4797', '10.89', '15592', '53581', '0.82', '145680', '46.00', '1.23', '65383', '26.00', '37.14', '29.37', '8129', '123', '118262', '17.59']
['18', '16', '-2', 'Infosys', 'Diversified\n                                              *', 'Infotech', '123936', '20.71', '121641', '21.07', '22110', '10', '14.26', '17.84', '200', '0.64', '17472', '5474', '0.07', '83998', '65.00', '-0.46', '67011', '22.00', '32.34', '39.66', '314015', '3', '684684', '-7.58']
['19', '15', '-4', 'Bharti Airtel', 'Mittal brothers & family', 'Telecommunication', '122048', '8.60', '116547', '15.83', '4255', '54', '0.00', '3.49', '16616', '29.31', '13494', '169678', '2.55', '274268', '26.00', '5.53', '66554', '23.00', '11.43', '11.26', '14774', '86', '409262', '17.31']
['20', '17', '-3', 'Coal India', 'GoI', 'Metals & Mining', '111310', '15.80', '109714', '21.87', '17358', '13', '36.68', '15.59', '541', '2.19', '29179', '3514', '0.08', '122082', '53.00', '7.41', '43143', '42.00', '43.63', '20.59', '251320', '4', '115608', '59.72']
['21', '30', '9', 'Steel Authority of India', 'GoI', 'Iron & Steel', '105033', '57.96', '103477', '49.72', '12243', '23', '195.16', '11.66', '1698', '8.09', '786', '17284', '0.32', '80950', '67.00', '-9.42', '54212', '32.00', '24.58', '21.13', '62181', '19', '37655', '-31.48']
['22', '25', '3', 'Grasim Industries', 'Aditya Birla Group', 'Diversified', '98340', '27.46', '89073', '27.30', '7550', '32', '75.38', '7.68', '4776', '34.78', '3253', '74733', '0.99', '249863', '29.00', '7.55', '75698', '19.00', '15.87', '8.86', '23591', '50', '106772', '-3.17']
['23', '31', '8', 'Nayara Energy\n                                                      ^', 'MNC', 'Oil & gas', '97354', '50.51', '93889', '49.65', '921', '174', '101.00', '0.95', '1840', '39.25', '2529', '18358', '0.85', '48987', '96.00', '4.93', '21642', '75.00', '4.35', '6.40', '4382', '188', 'NAP', 'NAP']
['24', '34', '10', 'GAIL (India)', 'GoI', 'Oil & Gas', '95970', '60.56', '92770', '61.70', '12256', '22', '99.73', '12.77', '202', '1.34', '2804', '9216', '0.14', '80013', '70.00', '19.55', '64114', '27.00', '20.98', '21.37', '13935', '88', '62828', '-2.14']
['25', '26', '1', 'Mahindra & Mahindra', 'M&M Group', 'Auto', '94407', '22.70', '90171', '21.40', '6577', '34', '262.89', '6.97', '5018', '34.58', '11118', '77605', '1.65', '142586', '48.00', '2.40', '47123', '40.00', '16.35', '10.93', '21297', '57', '124049', '56.36']
['26', '19', '-7', 'Canara Bank', 'GoI', 'Banking', '94257', '0.98', '70614', '0.51', '6125', '37', '111.89', '6.50', '43035', 'NAP', '182391', '1132626', '0.00', '1257664', '7.00', '6.62', '61455', '30.00', '10.03', '0.50', '86919', '15', '40385', '40.02']
['27', '28', '1', 'Maruti Suzuki India', 'MNC', 'Auto', '90330', '23.39', '88330', '25.52', '3880', '60', '-11.61', '4.29', '127', '2.22', '3042', '426', '0.01', '58025', '87.00', '5.09', '55334', '31.00', '5.24', '5.83', '16259', '79', '245546', '25.97']
['28', '18', '-10', 'Punjab National Bank', 'GoI', 'Banking', '88571', '-6.48', '76242', '-6.95', '3861', '61', '50.69', '4.36', '46823', 'NAP', '134194', '1213606', '0.00', '1340471', '6.00', '4.64', '90533', '13.00', '4.44', '0.29', '103144', '12', '39633', '3.39']
['29', '21', '-8', 'Bank of Baroda', 'GoI', 'Banking', '87780', '-2.00', '73385', '-1.25', '7850', '31', '407.19', '8.94', '38815', 'NAP', '130229', '1185331', '0.00', '1343104', '5.00', '11.42', '91868', '12.00', '8.37', '0.62', 'NAVL', 'NAP', '56318', '53.63']
['30', '27', '-3', 'HCL Technologies', 'Shiv Nadar', 'Infotech', '86785', '13.73', '85651', '13.63', '13499', '20', '21.12', '15.55', '319', '1.55', '12636', '6343', '0.10', '70907', '78.00', '1.59', '61914', '29.00', '22.20', '24.59', '112498', '9', '291346', '-8.28']
['31', '23', '-8', 'Axis Bank', 'Diversified\n                                              *', 'Banking', '86114', '10.44', '68846', '6.91', '14119', '17', '96.22', '16.40', '34923', 'NAP', '112344', '1020692', '0.00', '1195726', '10.00', '19.45', '118261', '9.00', '12.77', '1.29', '85815', '16', '223726', '20.59']
['32', '22', '-10', 'Union Bank of India', 'GoI', 'Banking', '81754', '-2.23', '68230', '-1.56', '5265', '43', '83.88', '6.44', '40178', 'NAP', '119758', '1085613', '0.00', '1196965', '9.00', '10.25', '66104', '24.00', '8.27', '0.46', '75201', '17', '28662', '21.74']
['33', '32', '-1', 'Wipro', 'Azim Premji', 'Infotech', '81416', '26.60', '79312', '28.06', '12230', '24', '13.27', '15.02', '533', '3.19', '10384', '17593', '0.27', '85887', '64.00', '27.01', '65403', '25.00', '20.35', '20.45', '247073', '5', '284287', '-40.42']
['34', '29', '-5', 'Power Finance Corporation', 'GoI', 'NBFC', '76345', '6.47', '76262', '6.43', '14015', '18', '19.30', '18.36', '44709', 'NAP', '6685', '660476', '9.21', '756751', '12.00', '2.06', '71676', '20.00', '28.34', '9.38', '501', '381', '30494', '-5.58']
['35', '33', '-2', 'Bajaj Finserv', 'Bajaj Group', 'NBFC', '68439', '12.95', '68406', '12.90', '4557', '50', '1.93', '6.66', '9629', 'NAP', '4403', '161179', '4.00', '227499', '35.00', '21.82', '40247', '45.00', '21.86', '11.43', '114', '397', '247652', '-3.88']
['36', '35', '-1', 'Samvardhana Motherson International', 'Vivek Chaand Sehgal', 'Auto Ancillaries', '64663', '11.12', '63536', '10.75', '874', '181', '-15.92', '1.35', '543', '12.29', '4999', '14130', '0.69', '38062', '111.00', '26.29', '20588', '80.00', '7.13', '7.47', '102422', '13', '61194', '-49.18']
['37', '37', '0', 'ITC', 'Diversified\n                                              *', 'FMCG', '63208', '20.28', '60668', '23.13', '15243', '16', '15.82', '24.12', '60', '0.29', '4654', '249', '0.00', '63473', '80.00', '3.29', '62456', '28.00', '25.25', '33.49', '23829', '48', '329683', '60.80']
['38', '36', '-2', 'Kotak Mahindra Bank', 'Uday Kotak', 'Banking', '59051', '4.69', '33740', '2.80', '12089', '25', '21.01', '20.47', '11553', 'NAP', '52665', '365235', '0.00', '546715', '16.00', '14.13', '96665', '11.00', '13.14', '2.36', '90000', '14', '365100', '-8.57']
['39', 'NAP', 'R-E 2011', 'Adani Wilmar\n                                                      (**)', 'Adani Group', 'Food & Agri Products', '53808', '45.50', '51879', '44.38', '804', '197', '10.33', '1.49', '541', '31.15', '4494', '2701', '0.36', '10808', '200.00', '60.14', '7606', '163.00', '14.20', '18.22', '2409', '271', '79083', '153.45']
['40', '42', '2', 'UltraTech Cement', 'Aditya Birla Group', 'Cement', '53651', '18.82', '52599', '17.60', '7344', '33', '34.43', '13.69', '945', '8.20', '359', '11299', '0.22', '62657', '82.00', '-6.27', '50435', '35.00', '15.50', '14.62', '21921', '53', '191756', '-13.14']
['41', '40', '-1', 'Hindustan Unilever', 'MNC', 'FMCG', '52909', '10.32', '52446', '11.52', '8879', '29', '11.06', '16.78', '106', '0.84', '3846', '1043', '0.02', '53398', '90.00', '2.80', '49061', '37.00', '18.38', '22.76', '8480', '122', '554507', '6.78']
['42', '38', '-4', 'Jindal Steel & Power', 'Savitri Devi Jindal', 'Iron & Steel', '51993', '48.92', '51166', '47.97', '5753', '40', '58.33', '11.07', '1888', '13.86', '3669', '13502', '0.38', '51135', '94.00', '-16.73', '35625', '50.00', '20.07', '20.68', '6200', '149', '42641', '7.33']
['43', 'NAP', 'R-E 2020', 'GIC', 'GoI', 'Financial Services', '49739', '2.36', '49585', '2.06', '2386', '81', '19.82', '4.80', '0', 'NAP', '21451', '0', '0.00', '60045', '85.00', '12.28', '36008', '49.00', '6.42', '6.61', 'NAVL', 'NAP', '22036', '-5.23']
['44', '45', '1', 'Hyundai Motor India\n                                                      ^', 'MNC', 'Auto', '48028', '16.29', '47378', '15.64', '2902', '72', '54.24', '6.04', '132', '2.40', '14139', '1178', '0.07', '19546', '145.00', '7.86', '16856', '94.00', '18.04', '20.73', 'NAVL', 'NAP', 'NAP', 'NAP']
['45', '46', '1', 'UPL', 'R.D. Shroff', 'Fert, Agrochem', '46655', '19.65', '46240', '19.50', '3626', '63', '26.30', '7.77', '2295', '24.93', '6120', '26746', '1.08', '56523', '89.00', '13.19', '24661', '68.00', '19.48', '14.80', '5456', '161', '56255', '2.02']
['46', '39', '-7', 'Bank of India', 'GoI', 'Banking', '46373', '-2.64', '38281', '-6.30', '3493', '65', '67.69', '7.53', '24083', 'NAP', '91709', '656802', '0.00', '745089', '13.00', '1.38', '49540', '36.00', '7.48', '0.47', '51825', '21', '20696', '4.17']
['47', '44', '-3', 'Power Grid Corporation of India', 'GoI', 'Power', '46342', '11.66', '41616', '4.99', '16824', '14', '39.78', '36.30', '8036', '22.45', '5048', '134696', '1.77', '215226', '39.00', '-1.08', '76247', '18.00', '19.39', '11.25', '8536', '120', '149824', '30.61']
['48', '52', '4', 'Tata Power Company', 'Tata Group', 'Power', '46298', '32.39', '43095', '30.11', '1741', '97', '54.47', '3.76', '3859', '59.25', '6641', '51195', '2.28', '88375', '62.00', '10.35', '22442', '72.00', '9.63', '7.90', '21636', '54', '73763', '2.11']
['49', '41', '-8', 'Indian Bank', 'GoI', 'Banking', '46268', '2.32', '38862', '-0.63', '4142', '56', '31.52', '8.95', '22129', 'NAP', '79968', '610724', '0.00', '674096', '15.00', '7.76', '38741', '46.00', '11.03', '0.64', '39803', '23', '20583', '53.92']
['50', '47', '-3', 'Tech Mahindra', 'Mahindra Group', 'Infotech', '45761', '18.42', '44646', '17.94', '5566', '42', '25.70', '12.16', '163', '2.03', '3975', '2618', '0.10', '33667', '114.00', '7.73', '26886', '61.00', '21.76', '23.78', '104583', '11', '126060', '-27.40']
['51', '59', '8', 'Petronet LNG', 'GoI', 'Oil & Gas', '43565', '65.01', '43169', '65.89', '3438', '66', '16.97', '7.89', '317', '6.05', '4326', '3439', '0.25', '18098', '148.00', '10.06', '13668', '111.00', '26.99', '28.24', '532', '379', '32191', '-6.87']
['52', '50', '-2', 'Sun Pharmaceuticals Industries', 'Dilip Shanghvi', 'Drugs, pharma', '39838', '13.84', '38654', '15.39', '3273', '67', '12.70', '8.22', '127', '2.24', '5033', '1290', '0.03', '53376', '91.00', '-1.97', '48011', '38.00', '14.50', '17.97', '19021', '66', '208246', '26.56']
['53', '48', '-5', 'REC', 'GoI', 'NBFC', '39339', '10.58', '39276', '10.46', '10036', '27', '19.78', '25.51', '22051', 'NAP', '2660', '333043', '6.49', '384357', '21.00', '2.91', '51314', '34.00', '21.11', '9.10', '442', '385', '25694', '0.64']
['54', '43', '-11', 'Vodafone Idea', 'MNC', 'Telecommunication', '38849', '-12.98', '38516', '-8.19', '-28245', '500', '0.00', 'NAP', '20981', '131.15', '3497', '40647', '0.00', '159273', '43.00', '-6.54', '-61965', '500.00', 'NAP', 'NAP', 'NAVL', 'NAP', '31106', '-15.27']
['55', '49', '-6', 'IndusInd Bank', 'Hinduja Group', 'Banking', '38230', '7.69', '30822', '6.29', '4805', '48', '63.99', '12.57', '15822', 'NAP', '68585', '340673', '0.00', '402333', '19.00', '10.76', '47719', '39.00', '10.57', '1.26', '33582', '25', '75633', '-6.24']
['56', '51', '-5', 'Nabard\n                                                      ^', 'GoI', 'NBFC', '37175', '6.19', '36905', '6.00', '5179', '45', '18.06', '13.93', '26574', 'NAP', '6073', '646380', '0.00', '758469', '11.00', '15.15', '90061', '14.00', '6.08', '0.73', 'NAVL', 'NAP', 'NAP', 'NAP']
['57', '53', '-4', 'New India Assurance Company', 'GoI', 'Insurance', '35916', '8.52', '35821', '8.33', '195', '386', '-88.14', '0.54', '0', 'NAP', '12629', '0', '0.00', '39909', '106.00', '3.55', '25805', '65.00', '0.69', '0.47', '13929', '89', '18381', '-41.68']
['58', '56', '-2', 'Bajaj Auto', 'Bajaj Group', 'Auto', '35637', '20.63', '33145', '19.48', '6166', '36', '26.95', '17.30', '9', '0.16', '958', '123', '0.00', '30020', '122.00', '9.42', '29860', '59.00', '19.01', '23.39', '7317', '134', '105551', '2.19']
['59', '80', '21', 'Titan Company', 'Tata Group', 'Gems & Jewellery', '33828', '55.83', '28799', '33.06', '2173', '87', '123.33', '6.42', '218', '6.63', '1573', '7275', '0.78', '16811', '156.00', '26.40', '9303', '143.00', '26.17', '20.76', '7263', '135', '214331', '14.81']
['60', '58', '-2', 'Adani Power', 'Adani Group', 'Power', '31686', '12.56', '27711', '5.68', '4912', '47', '286.74', '15.50', '4095', '41.72', '2365', '48744', '2.58', '73270', '76.00', '2.89', '18457', '87.00', '17.84', '12.71', 'NAVL', 'NAP', '88754', '224.70']
['61', '63', '2', 'Avenue Supermarts', 'R.K. Damani', 'Retail Trade', '31588', '28.20', '30976', '28.30', '1493', '117', '35.75', '4.73', '54', '2.15', '299', '647', '0.05', '14330', '165.00', '13.91', '13678', '110.00', '11.54', '15.74', '11312', '101', '272254', '-5.21']
['62', '55', '-7', 'Max Financial Services', 'Diversified\n                                              *', 'Diversified', '31188', '-0.32', '31182', '-0.30', '253', '361', '-40.44', '0.81', '25', 'NAP', '600', '522', '0.13', '5007', '299.00', '38.76', '3935', '253.00', '6.44', '7.94', 'NAVL', 'NAP', '28899', '-28.46']
['63', '66', '3', 'Asian Paints', 'Diversified\n                                              *', 'FMCG', '30838', '39.31', '29101', '34.03', '3031', '69', '-3.46', '9.83', '95', '2.04', '864', '1587', '0.11', '16009', '159.00', '10.06', '13812', '109.00', '23.18', '28.80', '7423', '133', '302270', '0.24']
['64', '68', '4', 'MMTC-PAMP India\n                                                      ^', 'MNC', 'Mining & minerals', '30488', '43.80', '29278', '43.71', '42', '437', '1,373.85', '0.14', '68', '46.47', '80', '611', '1.75', '992', '489.00', '-0.78', '348', '472.00', '24.92', '17.96', 'NAVL', 'NAP', 'NAP', 'NAP']
['65', '54', '-11', 'Hero MotoCorp', 'Munjal family', 'Auto', '30078', '-5.33', '29551', '-4.55', '2317', '83', '-20.59', '7.70', '53', '1.64', '300', '605', '0.04', '16936', '155.00', '2.86', '15847', '97.00', '14.90', '18.79', '9173', '109', '52027', '3.33']
['66', '62', '-4', 'Ambuja Cements', 'MNC\n                                              (Adani Group bought Ambuja-ACC in May 2022)', 'Cement', '29868', '20.81', '28965', '18.15', '2780', '73', '17.54', '9.31', '146', '2.39', '11694', '477', '0.02', '33294', '117.00', '11.42', '25354', '66.00', '15.43', '21.37', '4723', '179', '77109', '32.89']
['67', '101', '34', 'Indus Towers', 'Diversified\n                                              *', 'Telecom (Ancillaries)', '28176', '85.16', '27717', '98.63', '6373', '35', '68.65', '22.62', '1603', '10.76', '980', '19726', '0.89', '44313', '99.00', '11.45', '22151', '74.00', '33.52', '23.87', '3248', '221', '60720', '-30.92']
['68', '94', '26', 'NMDC', 'GoI', 'Metals & Mining', '27801', '75.03', '25882', '68.39', '9379', '28', '49.43', '33.74', '39', '0.31', '7978', '3491', '0.10', '39734', '107.00', '20.42', '34987', '52.00', '28.95', '35.80', '5539', '159', '39349', '7.44']
['69', '77', '8', 'Oil India', 'GoI', 'Oil & Gas', '27427', '40.68', '25906', '47.06', '5622', '41', '59.35', '20.50', '940', '8.95', '1550', '16721', '0.55', '51084', '95.00', '11.44', '30562', '58.00', '24.78', '21.32', 'NAVL', 'NAP', '23212', '-8.29']
['70', '70', '0', 'Ashok Leyland', 'Hinduja Group', 'Auto', '26725', '29.88', '26596', '34.64', '-359', '471', '0.00', 'NAP', '1869', '79.23', '2099', '24145', '3.31', '33356', '116.00', '-1.38', '7304', '169.00', 'NAP', '6.13', '10101', '104', '39945', '7.03']
['71', '97', '26', 'Interglobe Aviation', 'Rahul Bhatia', 'Airline Services', '26658', '70.05', '25931', '77.12', '-6162', '497', '0.00', 'NAP', '2386', '414.77', '10120', '36878', '0.00', '34948', '113.00', '4.87', '-5988', '496.00', 'NAP', 'NAP', '26164', '40', '73223', '-18.37']

In [64]:

# Create a DataFrame from the data_rows list
df = pd.DataFrame(data_rows, columns = filtered_titles_without_first_three)

# Display the DataFrame
df

,2022,2021,Change,Company,Ownership,Industry,Rs cr,YoY change %,Rs cr,YoY change %,...,Rank,YoY change %,Rs cr,Rank,(%),(%),(in nos),Rank,RS Crore,(%)
0,1,1,0,Reliance Industries,Mukesh Ambani,Oil & Gas,739518,43.81,699962,49.91,...,8.00,11.54,779485,1.00,9.17,9.36,342982,2,1681013,0.78
1,2,NAP,NEW,LIC,GoI,Financial Services,724744,2.99,723606,4.73,...,2.00,11.64,11336,130.00,45.28,0.31,NAVL,NAP,433115,-30.85
2,3,3,0,Indian Oil Corporation,GoI,Oil & Gas,607365,62.04,589336,61.93,...,27.00,16.36,133535,8.00,20.97,15.29,31254,26,108577,-13.70
3,4,4,0,ONGC,GoI,Oil & gas,502474,54.51,491270,61.66,...,17.00,6.09,259503,3.00,20.52,14.62,27165,36,188068,-6.05
4,5,2,-3,State Bank of India,GoI,Banking,406973,5.61,289973,4.26,...,1.00,10.64,282210,2.00,13.61,0.69,245652,6,447533,13.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,482,-14,Usha Martin,Brij Kishore Jhawar,Iron & Steel,2812,32.86,2688,28.17,...,425.00,8.43,1694,393.00,16.84,16.99,2180,287,3522,58.29
496,497,402,-95,Godfrey Phillips India,K.K. Modi Group,FMCG,2812,2.41,2706,6.42,...,369.00,9.49,2928,300.00,13.61,16.51,962,361,6003,19.19
497,498,NAP,NEW,Schwing Stetter India\n ...,MNC,Capital goods,2801,86.82,2539,62.64,...,494.00,8.53,438,470.00,11.45,13.86,NAVL,NAP,NAP,NAP
498,499,490,-9,Hubergroup India\n ...,MNC,Basic Materials,2797,0.00,2695,0.00,...,436.00,0.00,1764,384.00,9.92,13.12,NAVL,NAP,NAP,NAP
499,500,NAP,NEW,Nitin Spinners\n ...,Ratan Lal Nolkha,Textiles & Garments,2788,68.79,2692,65.74,...,464.00,1.59,876,449.00,45.32,36.06,5205,167,1350,-15

In [65]:
df.to_csv(r'I:\project\fortune_500_india_data.csv', index=False)